//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Has.Host.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry
    {
        public int Id { get; set; }
        public string InquiryCode { get; set; }
        public InquiryType InquiryType { get; set; }
        public Type City { get; set; }
        public string Region { get; set; }
        public string ClientName { get; set; }
        public string Address { get; set; }
        public string Comments { get; set; }
        public string Quotation { get; set; }
    }
}
