//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Has.Host.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStageCheckList
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int StagesId { get; set; }
        public int CheckListId { get; set; }
        public string Status { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Stages Stage { get; set; }
        public virtual CheckList CheckList { get; set; }
    }
}
