//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Has.Host.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectStageCheckLists = new HashSet<ProjectStageCheckList>();
        }
    
        public int Id { get; set; }
        public string ClientCode { get; set; }
        public string Status { get; set; }
        public string Stage { get; set; }
        public int StagesId { get; set; }
        public string Payment { get; set; }
        public string Material { get; set; }
        public string MaterialColor { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Drawing { get; set; }
    
        public virtual Stages Stage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectStageCheckList> ProjectStageCheckLists { get; set; }
    }
}
