//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Has.Host.Tests
{
    using System;
    
    public enum Type : int
    {
        Reference = 1,
        Direct = 2
    }
}
